services:
  ansible:
    build:
      context: .
      dockerfile: docker/ansible/Dockerfile
    image: ansible-control:local
    container_name: ansible-control
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - web_data:/web_data
    working_dir: /ansible
    depends_on:
      - web
      - backup
    networks:
      - devops-net

  web:
    build: docker/web
    volumes:
      - web_data:/usr/share/nginx/html
    ports:
      - "8090-8092:80"
    networks:
      - devops-net
    restart: unless-stopped

  backup:
    build: docker/backup
    volumes:
      - web_data:/backup/web
      - backup_storage:/backup/storage
    networks:
      - devops-net
    command: ["sleep", "infinity"]

volumes:
  web_data:
  backup_storage:

networks:
  devops-net:
    driver: bridge