services:
  ansible:
    build:
      context: .
      dockerfile: docker/ansible/Dockerfile
    image: ansible-control:local
    container_name: ansible
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - web-v:/web_data
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - TARGET_REPLICAS=${REPLICAS:-3}
    working_dir: /ansible
    depends_on:
      - web
      - backup
    networks:
      - network

  web:
    build: docker/web
    ports:
      - "8090-8092:3000"
    networks:
      - network

  backup:
    build: docker/backup
    container_name: backup
    volumes:
      - web-v:/backup/web
      - backup-v:/backup/storage
    networks:
      - network
    command: ["sleep", "infinity"]

volumes:
  web-v:
  backup-v:

networks:
  network:
    driver: bridge